### ISSUE TITLE
Bookmark and playback issues when signed into account. 

### ISSUE THREAD

**Issue by livebymisadventure** [dat1guy/UnofficialKissanime#1]
This addon has so much potential. I love the work on metadata. 
I needed to let you know that there is someone LOVING the direction this is going, I hope you continue.
The issue is this: The addon works as long as you switch to "https" in general settings and DO NOT sign in. If you sign in to your account after you've started the addon for the first time, you cannot access  your bookmarks but can play videos. And if you sign into your account BEFORE you first ever start the addon, your bookmarks list will load but nothing in the entire addon will load further or play.

Hopefully this will be fixed. If so, this will be my favorite addon BY FAR. 
Thanks.

**Comment by dat1guy** [comment]
Fixed with version 1.0.24.
