### ISSUE TITLE
Error connecting to TMDB: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by JorgeBoscan** [dat1guy/UnofficialKissanime#3]
Video's can't be played. The plugin logs:
21:08:16.788 T:7848   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
This is on Kodi 17 Krypton RC1

**Comment by dat1guy** [comment]
Hi Jorge,

What version of UKAP are you hitting this issue with?  I've been churning through a bunch of versions over the past few days, so the latest version (1.0.25) might have already solved your issue.

**Comment by JorgeBoscan** [comment]
I was using 1.0.23, just updated to 1.0.25 and still getting the same error.
08:04:39.751 T:11100   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
08:04:40.169 T:11100   ERROR: C:\Users\jorge\AppData\Roaming\Kodi\addons\script.module.beautifulsoup4\lib\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
                                            
                                            The code that caused this warning is on line 57 of the file C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py. To get rid of this warning, change code that looks like this:
                                            
                                             BeautifulSoup([your markup])
                                            
                                            to this:
                                            
                                             BeautifulSoup([your markup], "html.parser")
                                            
                                              markup_type=markup_type))

**Comment by JorgeBoscan** [comment]
Here's the whole stack:
08:35:47.976 T:7408  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
08:35:48.027 T:7408  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
08:35:48.315 T:7408   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
08:35:49.305 T:7408   ERROR: C:\Users\jorge\AppData\Roaming\Kodi\addons\script.module.beautifulsoup4\lib\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
                                            
                                            The code that caused this warning is on line 47 of the file C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py. To get rid of this warning, change code that looks like this:
                                            
                                             BeautifulSoup([your markup])
                                            
                                            to this:
                                            
                                             BeautifulSoup([your markup], "html.parser")
                                            
                                              markup_type=markup_type))
08:35:49.326 T:7408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find_all'
                                            Traceback (most recent call last):
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py", line 47, in <module>
                                                controller.Controller().show_quality()
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\common\controller.py", line 87, in show_quality
                                                self._show_list(QualityList())
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\common\controller.py", line 54, in _show_list
                                                list.parse()
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\list_types\quality_list.py", line 31, in parse
                                                self.links = self.soup.find(id='slcQualix').find_all('option')
                                            AttributeError: 'NoneType' object has no attribute 'find_all'
                                            -->End of Python script error report<--
08:35:49.375 T:19388   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.unofficialkissanime/?action=quality&base_mc_name=The%20Strongest%20Man&fanart=http%3a%2f%2fthetvdb.com%2fbanners%2ffanart%2foriginal%2f293088-11.jpg&full_mc_name&icon=http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f293088%2f5155243.jpg&imdb_id&media_type&srctype=web&tmdb_id&tvdb_id&value=%2fAnime%2fOne-Punch-Man%2fEpisode-001%3fid%3d116531
08:35:49.376 T:19388   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.unofficialkissanime/?action=quality&base_mc_name=The%20Strongest%20Man&fanart=http%3a%2f%2fthetvdb.com%2fbanners%2ffanart%2foriginal%2f293088-11.jpg&full_mc_name&icon=http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f293088%2f5155243.jpg&imdb_id&media_type&srctype=web&tmdb_id&tvdb_id&value=%2fAnime%2fOne-Punch-Man%2fEpisode-001%3fid%3d116531) failed
08:35:49.608 T:21028  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
08:35:49.656 T:21028  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
08:35:49.970 T:21028   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
08:35:50.989 T:21028   ERROR: C:\Users\jorge\AppData\Roaming\Kodi\addons\script.module.beautifulsoup4\lib\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
                                            
                                            The code that caused this warning is on line 45 of the file C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py. To get rid of this warning, change code that looks like this:
                                            
                                             BeautifulSoup([your markup])
                                            
                                            to this:
                                            
                                             BeautifulSoup([your markup], "html.parser")
                                            
                                              markup_type=markup_type))
08:35:51.044 T:21028  NOTICE: The Unofficial KissAnime Plugin: TIME DUMP for MediaContainerList.init
08:35:51.044 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****TOTAL: 0.000000
08:35:51.061 T:21028  NOTICE: The Unofficial KissAnime Plugin: TIME DUMP for MediaContainerList.add_items
08:35:51.061 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****Initial loop: 0.000000
08:35:51.061 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****Grabbing metadata with threads: 0.008000
08:35:51.061 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****Adding all items: 0.008000
08:35:51.061 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****TOTAL: 0.016000
08:35:51.229 T:21028  NOTICE: The Unofficial KissAnime Plugin: TIME DUMP for default.py
08:35:51.229 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****Default imports: 0.041000
08:35:51.229 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****Importing everything else: 0.405000
08:35:51.229 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****All non-imported execution: 1.259000
08:35:51.229 T:21028  NOTICE: The Unofficial KissAnime Plugin: ****TOTAL: 1.705000

**Comment by dat1guy** [comment]
Thanks for posting that.  The first two errors, the TMDB one and the BeautifulSoup HTML parser one, are both benign.  The exception is the real error that's causing Kodi to throw up the error flag.

I've been testing my addon on a bunch of shows with no problem, but it looks like One Punch Man is not working.  I'm able to reproduce the bug with this show, so thanks a ton for posting the log snippet.  I'll debug right now.

**Comment by dat1guy** [comment]
Actually, I know what this bug is.

Every video so far on KissAnime has been hosted on the KissAnime servers, so my add-on specifically looks for the video links on the KissAnime servers.  There have been a lot of changes on the website over the past few months, including using OpenLoad servers for some videos.  As of today, One Punch Man is *only* hosted on OpenLoad servers.  I know for a fact that it used to be on the KissAnime servers, so I'm not sure why they changed it.  Regardless, since my add-on doesn't currently try to get the video link from the OpenLoad servers, it's unable to play that show.  Implementing OpenLoad support would take a long time, so I'm probably not going to fix this any time soon.

I really do apologize.  The website keeps changing things, and it's hard to keep the add-on up to date with so many changes.  I'll leave this open so others can see the issue in case they run into this same problem.

**Comment by SultanMA** [comment]
Hi dat1guy, thank you for this great work you're doing.

I'm facing the same issue here but with all shows.
I checked the logs and it shows the same error.

I didn't change any configuration, and the version is 1.0.26

Looking forward for your input

**Comment by SultanMA** [comment]
You can view the whole logfile on this url:
https://paste.ubuntu.com/24201924/

**Comment by JorgeBoscan** [comment]
I forked your repo and tried to setup the enviroment so i can debug the addon but since I'm more of a Java/JS guy it's been a pain in the ass (I hate eclipse). I saw that exodus and salts can play openload videos, and I researched about it and saw some threads explaining that UrlResolver can actually extract the url that's needed for the player to reproduce the video. Don't know if you have thought about this approach, I'll try to get it working as soon as I can figure out how to stop the plugin from freezing when it's been monitored from a debug server

**Comment by dat1guy** [comment]
I'll take a look, but this is a feature request and not a bug, and I'm trying to iron out all the bugs first before adding anything else. That said, I'll try to get to this over the next week. If URLResolver can do this like you said, then the changes shouldn't be too big. Saturday, 18 March 2017, 08:35AM -07:00 from Jorge Boscan  notifications@github.com :

>I forked your repo and tried to setup the enviroment so i can debug the addon but since I'm more of a Java/JS guy it's been a pain in the ass (I hate eclipse). I saw that exodus and salts can play openload videos, and I researched about it and saw some threads
 explaining that UrlResolver can actually extract the url that's needed for the player to reproduce the video. Don't know if you have thought about this approach, I'll try to get it working as soon as I can figure out how to stop the plugin from freezing when
 it's been monitored from a debug server

**Comment by livebymisadventure** [comment]
Can confirm that unfortunately no shows, bookmarks or browse options (ie: poular, newest, ext..) are currently working on the latest version.

**Comment by dat1guy** [comment]
@JorgeBoscan I implemented support for Openload for version 1.0.3 if the KissAnime servers aren't available.  Shows like One Punch Man that don't have videos hosted on KissAnime servers and by default use Openload should work fine.

The caveat is that Openload support requires users to pair their computer with Openload, since I use the UrlResolver plugin for that, aka it's not something I control or implemented.  See [here](http://koditips.com/kodi-openload-pair-pairing-details-help/) for more information.

@SultanMA Please open up a new issue with the log, as you're hitting something different.  The bug you're hitting is something I cannot fix easily.  To give some context, video links hosted on KissAnime servers are now AES-encrypted with a key.  For some reason I don't understand, some users are getting different keys than others.  Since the add-on doesn't know everyone's keys, and it's not trying to find it, the add-on fails to decrypt the video links in such cases.  I created a technical workaround in v1.0.26 that most users won't be able to do without knowing JavaScript and the willingness to dive into the HTML and vr.js and deobfuscate that code.  I have some ideas for a real workaround, but I haven't thought it out too far yet...

@livebymisadventure Can you open a new issue and paste a log?

**Comment by JorgeBoscan** [comment]
@dat1guy Thanks man. I knew about the pairing protocol but it's better than nothing.

**Comment by JorgeBoscan** [comment]
Now that openload videos are resolved, there's still some videos that are not from that host that are still having problem. Here's the log for Dragon Ball Super Episode 01.

18:21:46.898 T:5748   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
18:21:48.704 T:5748   ERROR: C:\Users\jorge\AppData\Roaming\Kodi\addons\script.module.beautifulsoup4\lib\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
                                            
                                            The code that caused this warning is on line 47 of the file C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py. To get rid of this warning, change code that looks like this:
                                            
                                             BeautifulSoup([your markup])
                                            
                                            to this:
                                            
                                             BeautifulSoup([your markup], "html.parser")
                                            
                                              markup_type=markup_type))
18:21:48.743 T:5748   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid padding byte
                                            Traceback (most recent call last):
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\default.py", line 47, in <module>
                                                controller.Controller().show_quality()
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\common\controller.py", line 87, in show_quality
                                                self._show_list(QualityList())
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\common\controller.py", line 64, in _show_list
                                                list.add_items()
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\list_types\quality_list.py", line 51, in add_items
                                                link_val = self.decode_link(option['value'])
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\list_types\quality_list.py", line 71, in decode_link
                                                decrypted_link_val += decrypter.feed()
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\pyaes\blockfeeder.py", line 170, in feed
                                                result = self._final(self._buffer, self._padding)
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\pyaes\blockfeeder.py", line 79, in _block_final_decrypt
                                                return strip_PKCS7_padding(self.decrypt(data))
                                              File "C:\Users\jorge\AppData\Roaming\Kodi\addons\plugin.video.unofficialkissanime\resources\lib\pyaes\util.py", line 60, in strip_PKCS7_padding
                                                raise ValueError("invalid padding byte")
                                            ValueError: invalid padding byte
                                            -->End of Python script error report<--
18:21:48.818 T:16448   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.unofficialkissanime/?action=quality&base_mc_name=The%20Peace%20Prize.%20Who%27ll%20Get%20the%20100%20Million%20Zeny!&fanart=http%3a%2f%2fthetvdb.com%2fbanners%2ffanart%2foriginal%2f295068-11.jpg&full_mc_name&icon=http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f295068%2f5238715.jpg&imdb_id=tt4815348&media_type&srctype=web&tmdb_id&tvdb_id&value=%2fAnime%2fDragon-Ball-Super%2fEpisode-001%3fid%3d111869
18:21:48.819 T:16448   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.unofficialkissanime/?action=quality&base_mc_name=The%20Peace%20Prize.%20Who%27ll%20Get%20the%20100%20Million%20Zeny!&fanart=http%3a%2f%2fthetvdb.com%2fbanners%2ffanart%2foriginal%2f295068-11.jpg&full_mc_name&icon=http%3a%2f%2fthetvdb.com%2fbanners%2fepisodes%2f295068%2f5238715.jpg&imdb_id=tt4815348&media_type&srctype=web&tmdb_id&tvdb_id&value=%2fAnime%2fDragon-Ball-Super%2fEpisode-001%3fid%3d111869) failed
18:21:49.047 T:16052  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
18:21:49.097 T:16052  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
18:21:49.399 T:16052   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
18:21:51.421 T:14516  NOTICE: [plugin.video.quasar] NOTI  library      ▶ doUpdateLibrary  Library updated
18:21:51.455 T:21308  NOTICE: VideoInfoScanner: Starting scan ..
18:21:52.078 T:21308  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
18:21:52.353 T:19392  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
18:21:52.406 T:19392  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2
18:21:52.718 T:19392   ERROR: metahandler: Error connecting to TMDB: HTTP Error 401: Unauthorized
18:21:52.831 T:18276  NOTICE: metahandler: Initializing MetaHandlers version: 2.9.0
18:21:52.880 T:18276  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.10.2

If it's the decryption key that keep changing, can you share how you obtain it?, so maybe I can make a webservice that serves the key for you, so you can obtain it before reproducing the videos.
