### ISSUE TITLE
If "enable metadata" is ticked in settings, every movie (but not tv shows) will give an error.

### ISSUE THREAD

**Issue by livebymisadventure** [dat1guy/UnofficialKissanime#6]
(Using 16.1.)
If you untick "enable metadata" some movies will give an error but others will play. But it seems as if no movies will play with metadata enabled.

Example: If metadata is ticked, "Dragon Ball Z Movie 01: The Dead Zone (Dub)" will not play but will play after metadata is disabled.
But "5 Centimeters Per Second (Dub)" will give an error with metadata enabled or disabled. 

I originally thought it was giving an error on any item without fanart metadata, but then realized the items I tried that didn't have fanart were movies. I  went and found multiple tv shows without fanart to test this and they all played nicely.

**Comment by livebymisadventure** [comment]
Here's the Log of me trying to access "5 Centimeters Per Second (Dub)" with metadata enabled:
(http://pastebin.com/k3ha2gF1)

**Comment by dat1guy** [comment]
Ah, I introduced that bug with version 1.2.2, when I added the context menu option to show the queue.  That's my bad.  Version 1.2.2.2 should fix that.

**Comment by livebymisadventure** [comment]
Great. I'll verify the fix in about 8 hours after I get off work. Thanks.

**Comment by livebymisadventure** [comment]
All problems officially resolved! Everything is now in FULL working order.
I know this last week has probably been frustrating but I can promise you that I am (and anyone else lucky enough to find this is) extremely thankful for all your hard work. Cheers mate. You're awesome. Glad you might be able to finally relax.

Also, I'm not sure where I would send requests, so I'll take this opportunity to ask: Seeing how good you are at what you do, would you ever consider developing an add-on for kisscartoon in the future?

**Comment by dat1guy** [comment]
I'll need to think about it.  I originally made these just for myself as a fun side project, and I'm not sure I want to get into the business of maintaining add-ons for sites that I have no relationship with.  But I'll definitely consider it.
